title: IdeaLab
email: 
description: >- # this means to ignore newlines until "baseurl:"
  My personal website and blog
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://emilkovacev.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  
# Build settings
remote-theme: emilkovacev/aeroplane
plugins:
  - jekyll-feed

